### ISSUE TITLE
Too many trees in Europe

### ISSUE THREAD

**Issue by ghost** [0ADMods/maps_random_by_kali#21]
In Mediterranean, there are too many trees placed in Europe

**Comment by ghost** [comment]
@elexis1 fixed: https://github.com/0ADMods/maps_random_by_kali/blob/master/maps/random/mediterranean.js

I think the issue was too many straggler trees, so I reduced their amount. I want to keep this a pretty resource-rich map, but I also increased the spacing between forests which should help.

**Comment by ghost** [comment]
[medit_updates.diff.txt](https://github.com/0ADMods/maps_random_by_kali/files/378730/medit_updates.diff.txt)

**Comment by elexis1** [comment]
For those files that are committed in svn, those issues shouldnt be closed as noone looks at closed issues anymore. So reopening this one until its fixed in svn too.

I played a bit with the values and it seems the min distance is the most important factor. Couldnt convince myself of proper forest numbers yet.

**Comment by ghost** [comment]
OK, I found the same in my fiddling as well. Good news is that using the treeCount variable or similar, we can define custom resource allocation per biome

**Comment by elexis1** [comment]
Fixed by http://trac.wildfiregames.com/changeset/18553 to 18556. There was also a bug where birch trees were placed in africa.
